plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	flatDir {
		dirs 'libs'
	}
	maven {
		url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1"
	}
	maven { url 'https://maven.aliyun.com/repository/public' }
	maven {
		url = "https://maven.shedaniel.me/"
	}

}

loom {
	splitEnvironmentSourceSets()

	runs {
		client {
			vmArgs "-Ddevauth.enabled=true"
		}
	}

	mods {
		"${mod_id}" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modRuntimeOnly("me.djtheredstoner:DevAuth-fabric:1.2.2")
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modClientImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modImplementation files("libs/fabric-carpet-1.21.11-1.4.194+v251223.jar")
	implementation 'org.jetbrains:annotations:24.0.1'
	compileOnly 'org.jetbrains:annotations:24.0.1'
	modImplementation "me.shedaniel.cloth:cloth-config-fabric:11.1.118"
}

processResources {
	inputs.property "version", project.version
	inputs.property "mod_id", project.mod_id
	inputs.property "mod_name", project.mod_name
	inputs.property "mod_homepage", project.mod_homepage
	inputs.property "mod_sources", project.mod_sources
	inputs.property "minecraft_dependency", project.minecraft_dependency
	inputs.property "minecraft_version_id", project.minecraft_version_id
	inputs.property "minecraft_version", project.minecraft_version
	inputs.property "loader_version", project.loader_version
	inputs.property "fabric_api_version", project.fabric_api_version

	filesMatching("fabric.mod.json") {
		expand project.properties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName
	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}