
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2

loader_version=0.19.3
loom_version=1.17.17

mod_version=1.0.0
maven_group=com.eun
archives_base_name=eun-carpet

fabric_api_version=0.156.0+26.2

mod_id=eun_carpet
mod_name=EUN Carpet Addition
mod_homepage=https://github.com/zhang132212/eun_carpet
mod_sources=https://github.com/zhang132212/eun_carpet
minecraft_dependency=26.2

minecraft_version_id=26_2
